#%RAML 1.0 Trait
headers:
  X-Cms-ClientId:
          required: true
          type: string
          example: "hfdgv-7653"
  X-Cms-ClientSecret:
    required: true
    type: string
    example: "hfdgvkjhg"