#%RAML 1.0 DataType
type: object
properties:
  firstName:
    required: true
    type: string
    example: "Kumar"
  lastName:
    required: false
    type: string
    example: "ravi"
  maritalStatus:
    required: false
    type: string
    example: "Married"
  title:
    required: true
    type: string
    enum:
      - Mr
      - Ms
    example: "Mr"
  gender:
    required: true
    type: string
    example: "Male"
  Occupation:
    required: false
    type: string
    example: "SoftwareEngineer"
  preferredName:
    required: false
    type: string
    example: "kumar"
  identity:
    required: true
    type: object
    properties:
      password:
        required: true
        type: string
        example: "asdf@123"
      phoneCountry:
        required: true
        type: string
        example: "+91"
      phoneNumber:
        required: true
        type: string
        example: "9848012345"
      email:
        required: true
        type: string
        example: "abc@gmail.com"
  address:
    required: true
    type: object
    properties:
      country:
        required: true
        type: string
        enum:
          - India
          - United State
          - UK
        example: "India"
      city:
        required: true
        type: string
        example: "Hyderabad"
      area:
        required: true
        type: string
        example: "KPHB Colony"
      province:
        required: true
        type: string
        example: "512532"
      placeOfResidence:
        required: true
        type: string
        example: "HNo-123/456, Second Street "